#!/bin/bash
topk=$1
for dir in image_sets/*; do
    for args in args/*.classify_args; do
        args_name=${args#args/} ## remove prefix
        args_name=${args_name%.classify_args} ## remove suffix
        echo $args #print path to args file 
        source $args #import environment variables from args file
        echo $args
        echo $DARKNET_DATA #print the args
        echo $DARKNET_CLASSIFY
        echo $DARKNET_WEIGHTS
        mkdir -p results
        ./classify_topk $topk $dir/* > results/$args_name.${dir%%_*}.results
    done
done
